name: Build

on:
  push:
  # tags:
  #   - v*

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Publish to Open VSX Registry
        id: publishToOpenVSX
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          # pat: ${{ secrets.OPEN_VSX_TOKEN }}
          pat: dummy
          dependencies: false
          dryRun: true

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          # pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          pat: dummy
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          dryRun: true
